<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <RootNamespace />
    <StartupObject>Sub Main</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\DesktopBackupTool.Domain\DesktopBackupTool.Domain.vbproj" />
    <ProjectReference Include="..\DesktopBackupTool.Application\DesktopBackupTool.Application.vbproj" />
    <ProjectReference Include="..\DesktopBackupTool.Infrastructure\DesktopBackupTool.Infrastructure.vbproj" />
  </ItemGroup>

</Project>